<a href="https://colab.research.google.com/github/Aarjugit/Predictive-Analysis/blob/main/markov'schains.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix vector multiplication , test case- if you are having A,B,C Park and find the day wise visit in park according to the values given in matrix. For parkA 0.3 remains in park A, 0.5 goes to park B, 0.2 goes to park C asnd so on

In [ ]:
import numpy as np
#define the transition matrix
#matrix define according to the chances go in park A,B,C..All for park A in one row cz every row is sum to 1.
#but acording to convention every column should be 1
#so we need to convert the raw sum to one into column sum to 1
#The idea of changing it is called as Transpose
T=np.array([[0.30,0.50,0.20],
            [0.40,0.40,0.20],
            [0.60,0.30,0.10]])
#take the transpose of T for making the chnages
#once you do transpose your columns will sum to 1
T=T.T
print(T)


[[0.3 0.4 0.6]
 [0.5 0.4 0.3]
 [0.2 0.2 0.1]]


In [ ]:
#iniial_state:100% chance of being in park B
initial_state=np.array([0,1,0])
print(initial_state)
#Now multiply transition matrix by initial state for Day 2
day_2_state=np.dot(T,initial_state)
print(day_2_state)
day_3_state=np.dot(T,day_2_state)
print(day_3_state)
day_4_state=np.dot(T,day_3_state)
print(day_4_state)
#The sum is always one ,You can see in output, You can not go beyond 1

[0 1 0]
[0.4 0.4 0.2]
[0.4  0.42 0.18]
[0.396 0.422 0.182]


In [ ]:
print(f"state after Day 2: {day_2_state}")
print(f"state after Day 3: {day_3_state}")
print(f"state after Day 4: {day_4_state}")

state after Day 2: [0.4 0.4 0.2]
state after Day 3: [0.4  0.42 0.18]
state after Day 4: [0.396 0.422 0.182]


so, now I want to know after 1000's of days.I will just put in a loop and do it for 10000 times.



simulate the evolution of a Markov chain over time.where the future state depends only on the present state, not on the past.



In [ ]:
import numpy as np
T_mat=np.array([[0.30,0.50,0.20],
                [0.40,0.40,0.20],
                [0.60,0.30,0.10]])
T_mat=T_mat.T
#you started from b , you can make changes to c, d as well. the result remains same
state=np.array([0,1,0])
#Simulate many Days
#iterate many times to approach the steady state
#got the resultant vector in each iteration and multiply with matrix
for i in range(10000):
  state=np.dot(T_mat,state)
print(f"steady_state:{state}")
print(np.sum(state))

steady_state:[0.39669421 0.4214876  0.18181818]
1.0000000000000007


In [19]:
import numpy as np
T=np.array([[0.1,0.3,0.2,0.2,0.1,0.1],
            [0.2,0.1,0.3,0.2,0.1,0.1],
            [0.1,0.2,0.1,0.3,0.2,0.1],
            [0.1,0,0,0,0,0],
            [0,0,0,0,0,1],
            [0.2,0.1,0.2,0,0,0.5]])
T=T.T
state=np.array([0,0,1,0,0,0])

for _ in range(10000):
  state = np.dot(T,state)
print(f"steady_state:{state}")
print(np.sum(state))


steady_state:[2.5e-323 1.5e-323 2.5e-323 1.5e-323 9.9e-324 4.0e-323]
1.3e-322
